version: '3'
services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    command: npm run dev
    expose:
      - 3000
    ports:
      - "3000:3000"
    volumes:
      - .:/app
  db:
    image: postgres:latest
    volumes:
      - db-store:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: healthy
    restart: always

volumes:
  db-store: